### ISSUE TITLE
Nested Scrolls

### ISSUE THREAD

**Issue by TankyO** [flesler/jquery.serialScroll#11]
Hello!

First of all, great plugin! Thank you!

It's not really an issue but I didn't know where else to post that question.

I'm currently trying to build a layout with nested scrolls.
A splitted view of the window with a viewer in each part (left & right).
Each viewer contains a grid formed by <ul> (rows) which contain <li> (lines).
I'd like to be able to scroll thought the rows and then thought the lines in the active row.

Here is a fiddle:

http://jsfiddle.net/Tancrede/93eas6po/

It's almost working but the two systems seem to collapse.
As my knowledge in jQuery and Javascript is very limited, I was wondering if you could help me?

Best Regards,
Tancrède

**Comment by ottiger** [comment]
An updated fiddle:
http://jsfiddle.net/Tancrede/93eas6po/2/

One of the bugs occurs when you first go down a few steps in the first row then, try to go right (next).

**Comment by flesler** [comment]
Hi @TankyO 
This is the place to report potential bugs and features, not for user support.
You should post that on sites like StackOverflow where many more eyes will see it.
