### ISSUE TITLE
Demo page not working

### ISSUE THREAD

**Issue by Craigy-** [flesler/jquery.serialScroll#12]
I see "isNumeric" error in firebug.
Browser: Firefox 34.0.5, Win 8.1.

**Comment by flesler** [comment]
Latest version of serialScroll requires jQuery 1.7 or higher which includes $.isNumeric.

**Comment by Craigy-** [comment]
But in your demo page included 1.3.1.

**Comment by Craigy-** [comment]
But it not only one error in demo...

**Comment by flesler** [comment]
The [demo page](http://demos.flesler.com/jquery/serialScroll/) includes:
- jQuery 1.8.3
- scrollTo 1.4.11
- serialScroll 1.2.4

Not sure where you're looking at.

**Comment by flesler** [comment]
Oh I understand now, you tried the demo but changing the jQuery version.
The demo uses 1.2.4, the $.isNumeric change is very recent, I added that on 1.2.4.1 which is newer than the demo.

**Comment by flesler** [comment]
If you really need to use an old jQuery version, you can downgrade to serialScroll 1.2.4

**Comment by Craigy-** [comment]
Hmmm, I'm just downloaded zip of this repository, without any changes of mine... Did you try to open current demo/index.html?

**Comment by flesler** [comment]
Ok now I understood, the offline demo was indeed including 1.3.1 but the online wasn't
Thanks
